// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RequestContext.proto
// Protobuf Java Version: 4.34.1

package edu.sunrise.context;

@com.google.protobuf.Generated
public final class RequestContextProtos extends com.google.protobuf.GeneratedFile {
  private RequestContextProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RequestContextProtos");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_sunrise_context_RequestContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_edu_sunrise_context_RequestContext_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024RequestContext.proto\022\023edu.sunrise.cont" +
      "ext\"9\n\016RequestContext\022\014\n\004name\030\001 \001(\t\022\n\n\002i" +
      "d\030\002 \001(\005\022\r\n\005email\030\003 \001(\tB-\n\023edu.sunrise.co" +
      "ntextB\024RequestContextProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_edu_sunrise_context_RequestContext_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_edu_sunrise_context_RequestContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_edu_sunrise_context_RequestContext_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
